### ISSUE TITLE
[AVM Module Issue]: Update remaining modules' Private Endpoints schema once they pass in main

### ISSUE THREAD

**Issue by krbar** [Azure/bicep-registry-modules#3159]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Diverse modules currently fail in main (e.g., due to WAF-reliablity) and can hence not be updated with to lastest Private Endpoints schema as they'd just fail in main again without publishing the update.

This issue is intended to track these modules to enable a future update as they are fixed.

cc: @AlexanderSehr 

```[tasklist]
### Tasks
- [x] update PE schema in `avm/res/cognitive-services/account` (#3521)
- [x] update PE schema in `avm/res/container-registry/registry` (#3215)
- [x] update PE schema in `avm/res/desktop-virtualization/host-pool` (#3170)
- [ ] update PE schema in `avm/res/digital-twins/digital-twins-instance`
- [x] update PE schema in `avm/res/storage/storage-account` (not failing in main, but the PR #2997 was already open before started the bulk updates)
```

| Status of remaining modules |
| - | 
[![avm.res.cognitive-services.account](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.cognitive-services.account.yml/badge.svg?branch=main)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.cognitive-services.account.yml)
[![avm.res.digital-twins.digital-twins-instance](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.digital-twins.digital-twins-instance.yml/badge.svg?branch=main)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.digital-twins.digital-twins-instance.yml)

**Comment by krbar** [comment]
@AlexanderSehr It looks like this one can be closed too. All modules from the list are updated and the repository does not contain any modules, which reference the `br/public:avm/res/network/private-endpoint` prior the version 0.7.1...
